services:
  premiscale: &premiscale
    container_name: premiscale
    platform: linux/amd64
    profiles:
      - zero
    build:
      context: .
      dockerfile: ./Dockerfile
      target: develop
      pull: true
    env_file:
      - .env
    environment:
      - PREMISCALE_TOKEN=123
      - PREMISCALE_CONFIG_PATH=/opt/premiscale/config.yaml
      - PREMISCALE_LOG_LEVEL=debug
      - PREMISCALE_PLATFORM=platform:443
      - PREMISCALE_CACERT=/opt/premiscale/cert.pem
      - INFLUXDB_HOST=influxdb:8086
      - INFLUXDB_USERNAME=premiscale
      - INFLUXDB_PASSWORD=premiscale
      - MYSQL_HOST=mysql-agent-state:3306
      - MYSQL_USERNAME=premiscale
      - MYSQL_PASSWORD=premiscale
      - PREMISCALE_TEST_SSH_KEY=$PREMISCALE_TEST_SSH_KEY
    networks:
      - controller
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 1G
    depends_on:
      mysql-agent-state:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      echoes:
        condition: service_healthy
      registration:
        condition: service_healthy
      platform:
        condition: service_healthy
    volumes:
      - ./certs/cert.pem:/opt/premiscale/cert.pem:ro
    healthcheck:
      test: curl http://localhost:8085/healthcheck
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - 8085:8085
  ##
  premiscale-two-hosts-influxdb:
    <<: *premiscale
    container_name: premiscale-two-hosts-influxdb
    profiles:
      - two_hosts_influxdb
    volumes:
      - ./certs/cert.pem:/opt/premiscale/cert.pem:ro
      # Mount a different config from the default into the running container for testing.
      - ./src/tests/data/config/v1alpha1_base+qemu_two_hosts_no_asg_influxdb.yaml:/opt/premiscale/config.yaml
  ##
  premiscale-two-hosts: &premiscale-two-hosts
    <<: *premiscale
    container_name: premiscale-two-hosts
    profiles:
      - two_hosts
    volumes:
      - ./certs/cert.pem:/opt/premiscale/cert.pem:ro
      # Mount a different config from the default into the running container for testing.
      - ./src/tests/data/config/v1alpha1_base+qemu_two_hosts_no_asg.yaml:/opt/premiscale/config.yaml
  ##
  premiscale-two-hosts-profile:
    <<: [*premiscale-two-hosts, *premiscale]
    container_name: premiscale-two-hosts-profile
    command: [ "bash", "-c", "poetry run memray run -o /opt/premiscale/output.bin premiscale --log-stdout --log-level=${PREMISCALE_LOG_LEVEL}" ]
    profiles:
      - two_hosts_profile
    volumes:
      - ./certs/cert.pem:/opt/premiscale/cert.pem:ro
      # Mount a different config from the default into the running container for testing.
      - ./src/tests/data/config/v1alpha1_base+qemu_zero_no_asg.yaml:/opt/premiscale/config.yaml
      # Mount the output file to the host for generating flamegraphs of the controller's performance.
      - ./profile/output.bin:/opt/premiscale/output.bin
  ##
  premiscale-single-host:
    <<: *premiscale
    container_name: premiscale-single-host
    profiles:
      - single_host
    volumes:
      - ./certs/cert.pem:/opt/premiscale/cert.pem:ro
      # Mount a different config from the default into the running container for testing.
      - ./src/tests/data/config/v1alpha1_base+qemu_single_host_no_asg.yaml:/opt/premiscale/config.yaml
  mysql-agent-state:
    container_name: mysql-agent
    image: mysql:9.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=premiscale
      - MYSQL_DATABASE=premiscale
      - MYSQL_USER=premiscale
      - MYSQL_PASSWORD=premiscale
    ports:
      - 3306:3306
    networks:
      - controller
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 1G
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
  influxdb:
    container_name: influxdb-agent
    image: influxdb:2.7.6
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=premiscale
      #- DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=premiscale
      - DOCKER_INFLUXDB_INIT_PASSWORD=premiscale
      - DOCKER_INFLUXDB_INIT_ORG=premiscale
      - DOCKER_INFLUXDB_INIT_BUCKET=premiscale
    ports:
      - 8086:8086
    networks:
      - controller
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 1G
    healthcheck:
      test: influx ping || exit 1
      interval: 3s
      retries: 5
      start_period: 5s
      timeout: 5s
  grafana:
    container_name: grafana
    image: grafana/grafana:9.5.20
    user: '0'
    restart: unless-stopped
    environment:
      - TERM=linux
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_SECURITY_ADMIN_PASSWORD=premiscale
      - GF_SECURITY_ADMIN_USER=premiscale
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ROLE=Viewer
      - GF_USERS_DEFAULT_THEME=light
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - GF_USERS_VIEWERS_CAN_SAVE_DASHBOARDS=true
      - GF_USERS_VIEWERS_CAN_SAVE_TEMPORARY=true
    ports:
      - 3000:3000
    networks:
      - controller
      - platform
      - default
    volumes:
      # Certs
      - ./certs/cert.pem:/etc/grafana/cert.pem:ro
      - ./certs/key.pem:/etc/grafana/key.pem:ro
      # SQLite data
      - grafana-data:/var/lib/grafana
      # Config
      - ./config/grafana/config.ini:/etc/grafana/grafana.ini:ro
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 1G
    depends_on:
      influxdb:
        condition: service_healthy
      mysql-grafana:
        condition: service_healthy
    healthcheck:
      test: curl http://localhost:3000
      interval: 3s
      retries: 5
      start_period: 5s
      timeout: 5s
  mysql-grafana:
    container_name: mysql-grafana
    image: mysql:9.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=premiscale
      - MYSQL_DATABASE=grafana
      - MYSQL_USER=premiscale
      - MYSQL_PASSWORD=premiscale
    ports:
      - 3308:3306
    networks:
      - controller
      - platform
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 1G
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 8s
      interval: 5s
      timeout: 5s
      retries: 5
  platform:
    container_name: nginx
    image: nginx:stable
    ports:
      - 443:443
    volumes:
      - ./config/nginx/compose.nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - platform
      - controller
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 300M
    healthcheck:
      test: curl http://localhost/healthcheck
      interval: 3s
      retries: 3
      start_period: 10s
      timeout: 5s
    depends_on:
      registration:
        condition: service_healthy
      echoes:
        condition: service_healthy
  # test:
  #   image: ubuntu:22.04
  #   command: sleep inf
  #   networks:
  #     - platform
  #     - controller
  #   volumes:
  #     - ./certs:/certs:ro
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: 300M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 300M
  echoes:
    container_name: premiscale-echoes
    build:
      context: ../echoes/
      dockerfile: Dockerfile.develop
    environment:
      - ECHOES_LISTEN_ADDRESS=0.0.0.0
      - ECHOES_LISTEN_HTTP_PORT=8081
      - ECHOES_LISTEN_WSS_PORT=8080
      - ECHOES_LOGLEVEL=debug
      - ECHOES_FLASK_WORKERS=1
      - MYSQL_USERNAME=premiscale
      - MYSQL_PASSWORD=premiscale
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3037
      - MYSQL_DATABASE=premiscale
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=premiscale
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - platform
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 1G
    depends_on:
      mysql-platform:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl http://localhost:$$ECHOES_LISTEN_HTTP_PORT/agent/websocket/healthcheck
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 3
  registration:
    container_name: premiscale-registration
    build:
      context: ../registration/
      dockerfile: Dockerfile.develop
    environment:
      - REGISTRATION_LISTEN_ADDRESS=0.0.0.0
      - REGISTRATION_LISTEN_PORT=8080
      - REGISTRATION_WORKERS=0
      - REGISTRATION_LOGLEVEL=debug
      - MYSQL_USERNAME=premiscale
      - MYSQL_PASSWORD=premiscale
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3037
      - MYSQL_DATABASE=premiscale
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=premiscale
    ports:
      - 8082:8080
    networks:
      - platform
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 1G
    depends_on:
      mysql-platform:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl http://localhost:$$REGISTRATION_LISTEN_PORT/agent/registration/healthcheck
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 3
  redis:
    container_name: redis
    image: redis:7.4.1
    environment:
      - REDIS_PASSWORD=premiscale
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_PASSWORD
    volumes:
      - redis-cache:/data
    healthcheck:
      test: redis-cli ping
      interval: 3s
      retries: 5
      start_period: 2s
      timeout: 3s
  mysql-platform:
    container_name: mysql-platform
    image: mysql:9.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=premiscale
      - MYSQL_DATABASE=premiscale
      - MYSQL_USER=premiscale
      - MYSQL_PASSWORD=premiscale
    ports:
      - 3307:3306
    networks:
      - platform
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 1G
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 15s
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  controller:
    driver: bridge
    internal: false
  platform:
    driver: bridge
    internal: false
volumes:
  redis-cache:
    driver: local
  grafana-data:
    driver: local